### ISSUE TITLE
Comment out a selection of text.

### ISSUE THREAD

**Issue by Jackojc** [jmacdonald/amp#100]
It would be nice if you could select a chunk of text and comment all of it out at once.

For example, if I select the following text:
```
code
code
more code
```
and I press some keybinding, I should get:
```
/*code
code
code*/
```
or something similar depending on the language.

Python uses only single line comments for example (Although you can use multi-line strings too.)

**Comment by jedahan** [comment]
On macOS I usually see this bound to command-/

**Comment by Cookizza** [comment]
Any word on how to do this?

**Comment by logankaser** [comment]
I also would love this feature!

**Comment by sjmackenzie** [comment]
I would also love this feature.
