### ISSUE TITLE
Suggestion: make highlight more obvious

### ISSUE THREAD

**Issue by jonathandturner** [jmacdonald/amp#106]
When doing a search, you can use the arrow keys to move around and select one of the options. Unfortunately, on some screens, it's very difficult to see the highlight. It may make sense to enhance the highlight by also having some kind of other indicator.

Eg) 

```
file1.rs
> file2.rs
file3.rs
```

Showing that the second one is the one that will be selected

**Comment by jmacdonald** [comment]
Thanks for the suggestion, @jonathandturner! This is now in master.
