### ISSUE TITLE
Line highlight in themes is not respected

### ISSUE THREAD

**Issue by kasperisager** [jmacdonald/amp#117]
I'm using a theme that sets `lineHighlight` to `#44475a` which causes the following odd blue color to be rendered:

<img width="610" alt="image" src="https://user-images.githubusercontent.com/1174718/48947619-ffde6100-ef31-11e8-98ca-fa2b2a3fe0af.png">

Any idea why this might be?

**Comment by jmacdonald** [comment]
Termbox only supports 8-bit color, so we [cast 24-bit colors to their 8-bit equivalents](https://github.com/jmacdonald/amp/blob/master/src/view/terminal/rustbox_terminal.rs#L139-L155) before rendering. The `termion` branch, once completed/merged, will bring 24-bit color support. :slightly_smiling_face:

**Comment by dontlaugh** [comment]
Looks like `termion` is on [master](https://github.com/jmacdonald/amp/blob/master/Cargo.toml#L29). Is this fixed?

**Comment by jmacdonald** [comment]
@dontlaugh it is; thanks for the nudge!
