### ISSUE TITLE
[question] how to refresh the buffer

### ISSUE THREAD

**Issue by ratmav** [jmacdonald/amp#140]
let's say, for some unknown uncontrollable reason, the file amp is modifying has been changed by some other process while the buffer is open. with vim, i'd call `e` or `edit!` or something similar and refresh all the buffers. does amp have a way to refresh the buffer when the underlying file changes?

**Comment by jmacdonald** [comment]
Yep! There’s a buffer::reload command that you can find in command mode, or
you can use its default Ctrl-r keybinding in normal mode.

Hope that helps. 🙂
-- 

–
Jordan
