### ISSUE TITLE
problems with version from master branch

### ISSUE THREAD

**Issue by pbgc** [jmacdonald/amp#146]
Hi,

Out of curiosity I built the version from master branch and tried to use it.
I got some problems ... with some actions giving me [A or [B characters inserted and ESC key not functioning (hence could not leave edit mode).

This, for example, happens doing this:
- Open a file
- Press i
- Press ESC and UP key right after

I'm on macOS 10.14.4

I filed this issue to try to help! I apologize if this is a known issue and WIP ... and in that case please close the issue.

Thanks!
Pedro Costa

**Comment by jmacdonald** [comment]
Hi Pedro!

Thanks for opening this issue. I haven't given the updated version a spin on MacOS, but amp's input model has fundamentally changed so it's entirely possible we've introduced a regression. I'll give this a go to see if I can reproduce.

**Comment by jmacdonald** [comment]
Ok @pbgc, using Alacritty on MacOS 10.14 doesn't expose the issue you're having. What terminal emulator are you using?

**Comment by pbgc** [comment]
Hi,

I'm using Alacritty 0.32 and just checked and this problem does not happen
on iterm2 or macOS terminal....

Strange because I use alacritty for a long time without any problem in any
app .. and use it with amp 0.52 without this one or any other problem.



A quinta, 16/05/2019, 02:53, Jordan MacDonald <notifications@github.com>
escreveu:

**Comment by pbgc** [comment]
Sorry... Just saw better what you wrote and saw that you are using also
alacritty.

Are you pressing the up arrow right after (not at the same time but very
fast after) the esc ?

I can send you a small video of me doing it because I just tried again and
it happens... And not only with this key combo. It happened also in some
other situations... But I described this one that was (I thought...) easy
to replicate.

A quinta, 16/05/2019, 02:53, Jordan MacDonald <notifications@github.com>
escreveu:

**Comment by pbgc** [comment]
@jmacdonald I finally solved this!

The problems above and several other strange things ... was being caused by the fact that there was a BIG delay on ESC key action !!!

Searching and after looking at:
https://github.com/jwilm/alacritty/issues/1680
that pointed me to: https://www.johnhawthorn.com/2012/09/vi-escape-delays/

adding the line
`set -s escape-time 0`
to my .tmux.conf file ... got all problems away!

I don't understand why this only was happening with Alacritty and not iterm2 or term ... and 0.52 worked without problem in all ... but now I'm not having any problem!

**Comment by jmacdonald** [comment]
@pbgc nice find! Thanks for sharing the solution, and closing this issue. :slightly_smiling_face:
