### ISSUE TITLE
pasting into amp warps text

### ISSUE THREAD

**Issue by sjmackenzie** [jmacdonald/amp#150]
## Steps to reproduce:
* copy text from somewhere
* paste into amp
## Expected behaviour
* indentation stays the same
## Actual behaviour 
* indentation gets messed up

**Comment by jmacdonald** [comment]
Hi @sjmackenzie! Thanks for filing this.

Are you trying to paste into amp using `Ctrl-v`? There's a built-in paste command that you can use by hitting `p` in normal mode; please try that and let me know if it works as expected.

**Comment by sjmackenzie** [comment]
Yup, right again! `p` works perfectly! thanks!
