### ISSUE TITLE
copying text out of amp includes line numbers

### ISSUE THREAD

**Issue by sjmackenzie** [jmacdonald/amp#151]
## steps to reproduce
* write something
* select and copy it
## expected behaviour
* line numbers are not copied
## actual behaviour
* line numbers are copied

**Comment by jmacdonald** [comment]
Hi @sjmackenzie! Are you selecting text using your cursor and then using the terminal emulator's copy functionality? If so, you'll want to use amp's [text selection mode](https://amp.rs/docs/usage/#selecting-text). Hitting `y` to copy the selected contents after that should solve this for you. :slightly_smiling_face:

**Comment by sjmackenzie** [comment]
why yes! great!
