### ISSUE TITLE
Shall we discuss the key mapping design?

### ISSUE THREAD

**Issue by icyhat** [jmacdonald/amp#153]
I love amp, brand new editor!

here is some notes of amp usage
```
[]       a pen poiting to screen
*        char, even <CR> is a char
..       token
...      chars of 1 Dimension on screen
___      blanks of chars of 1 Dimension on screen

target text
1. create
O/P
___  I  ... i*..a  ...  A
o/p
2. read
               K
              ...
               k
H  ...  b..?  h.l  w..e  L
               j
              ...
g + ??                   go to line
              ...
Esc                      centering line
              ...
m/,                      scroll forward/backward
              ...
f + ??
              ...
/ + ?? + n/N
              ...
v/V
              ...
C-a
              ...
               J

3. update
change to end of token    c
copy remote URL           R
copy line                 y
change to end of line     C
merge line                M
indent line               </>
undo                      u
redo                      r
theme                     t
save                      s
4. delete
char                      x
to end of token           d
to end of line            D
line                      ;

buffer
  new buffer  B
  suspend     z/C-z
  quit        q/C-c
  quit text   Q
  quit_other  F
```

what puzzle me is that current functions of amp is not enough for editing fluently. I wonder is there a statistic data or survey that can guide the new function added on amp are most needed?

In short, is there  a `Functions Priority Queue` that amp is going to implement? These features are Well discussed for Rust programming or generated by `Statistic Data`?

**Comment by jedahan** [comment]
My most common missing feature is ‘.’ for repeating the last command sequence. Even ‘q’ would help

**Comment by icyhat** [comment]
hello, author of amp~

I wonder how do you memory when learning Rust details?

In my imagination, I need *2 Trees* and *Links* to write all things down as Knowledge Management.

```
e.g.
1. target_tree
    1. saving time
        1. saving coding time
            1. auto-complement
            2. useful libs
        2. saving debug time
            1. Rust Rich Type System
            2. Ownership
    2. reduce money cost
        1. reduce machine cost
            1. efficiency
                1. Ownership
            2. predictable
                1. Ownership
2. what_rust_has_tree
    1. doc
    2. cargo
    3. language
        1. Ownership
            1. for safety
            2. for efficiency
            3. for predictable
        2. Concurrency
        3. struct and enum
```
The question is how can I jump `Ownership` from 1 tree to another tree?

When I am learning more and more about Rust, I can't memory all things, but when I write down somethings normally, my notes will grow into a `Big Mess` eventually.

The above two trees method is useful to memory
1. 1 tree is for what Rust has and how many usage does 1 mechanism has
2. 1 tree is for if we wanna 1 usage, how many multi mechanism Rust has

The problem is that I tried lots of mind map softwares or editors, no one satisfied, it should 
1. CRUD parent/sub element using modal editing like vi, which is now amp try to do
2. I can create 2 trees in 2 files or in 1 file by amp, but how can I connect the same thing together? when I  learn `Ownership`'s multi attributes , I can easily jump to target tree and see what other mechanism has same advantage?

Most important thing, will amp add symbolic link feature, or depending link or double link?

**Comment by icyhat** [comment]
Actually, what we need is to write down all `Net` model down, translate these objects into text, and this is why we have text editor.

To handle the the attributes of object or sub type of object,  a `tree` model is enough, such like `std::xxx::yyy`, `std::xxx::zzz`

But when write down relations between objects, `Rust lang` use `functions` to connect each objects together, one is input and other is output, `fn xx (x) -> y {}`, and what in `{}` is the sequence of `time`.

that's all and if we focus on how our brain works in handle information, the `text editor::amp` is kind of implementation, the details are not important any more, there only exist two things a `text editor` should offer:
1. a tree of what is one object
2. a connection between objects

I can use different indentation to simulate a different-levels of tree, but I can't find a simple way to add connections between objects, and one thing is nothing unless it connect to others, whether it's a reason or dependency or part of material or any effect to made other things.

**Comment by jmacdonald** [comment]
@icyhat it sounds like you're trying to use amp to build some kind of wiki, which is definitely not a goal of this project. I'd recommend you investigate a documentation system ([MkDocs](https://www.mkdocs.org/) is a great example of this). Amp is strictly focused on editing text files, and although it's able to parse symbols and help search/navigate files in and below the current directory, it doesn't provide any facility for defining those symbols, or relationships between them, outside of the language-specific syntax definitions it uses to parse them.

**Comment by icyhat** [comment]
Thanks for your explanations and suggestions.

Finally, I found `TheBrain` to hold `multi-extend` mechanism to link all things together fast and powerful.

If sometimes you feel mess in your brains about something, try it, it's much better than usual mind map software.

Good luck, have fun.
