### ISSUE TITLE
support v0.6.0 on homebrew

### ISSUE THREAD

**Issue by erf** [jmacdonald/amp#154]

**Comment by jmacdonald** [comment]
Hi @erf! Thanks for the nudge. I've [updated the Homebrew formula](https://github.com/jmacdonald/homebrew-amp/commit/54b8c75047baa2b66df4795a7d8f521b26ad9560). I don't run MacOS anymore; can you try it out and let me know if it builds for you?

**Comment by erf** [comment]
Hi @jmacdonald , it works! 

It did 6+ minutes to build though with no info.
