### ISSUE TITLE
Build errors on linux

### ISSUE THREAD

**Issue by srikk73** [jmacdonald/amp#155]
I got this error when building:
```
Updating registry `https://github.com/rust-lang/crates.io-index`
Installing amp v0.5.2
error: failed to compile `amp v0.5.2`, intermediate artifacts can be found at `/tmp/cargo-install7HSkwc`
`
Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/.../.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.33/Cargo.toml`

Caused by:
  editions are unstable

Caused by:
  feature `edition` is required
```

Can you please help here?

Regards,
Srik

**Comment by jmacdonald** [comment]
Hi @srikk73! It sounds like you're compiling amp on an older, unsupported version of Rust (pre-2018 edition).

**Comment by srikk73** [comment]
Hi,

I am using this;

```
$ rustc -V
rustc 1.29.1 (b801ae664 2018-09-20)
```

This looks like 2018 version, I think. Do correct me if I'm wrong.

Regards,
srik

**Comment by pbgc** [comment]
@srikk73 no! You have to use at least 1.31

https://blog.rust-lang.org/2018/12/06/Rust-1.31-and-rust-2018.html

**Comment by jmacdonald** [comment]
I've updated the documentation to reflect the minimum version of Rust required to compile amp. Thanks, @srikk73 and @pbgc!
