### ISSUE TITLE
0.6.0 release is not in cargo

### ISSUE THREAD

**Issue by Kinrany** [jmacdonald/amp#157]
I encountered the problem with termbox described in https://github.com/jmacdonald/amp/issues/136

This repo has [release 0.6.0][1] which was supposed to fix the problem, but it's not available in cargo. Is it supposed to be, or is it still in development?

[1]: https://github.com/jmacdonald/amp/releases/tag/0.6.0

**Comment by jmacdonald** [comment]
Hi @Kinrany! That was an oversight on my part. I've just published it; thanks for the nudge! :slightly_smiling_face:

**Comment by Kinrany** [comment]
You're welcome! I'm glad I ignored the "surely someone would mention it" thought and asked anyway :D
