### ISSUE TITLE
Scroll down/up with cursor

### ISSUE THREAD

**Issue by elshize** [jmacdonald/amp#158]
I noticed there are options for scrolling `m` and `;` but the cursor doesn't follow, so when you move it, it goes back. But I cannot find a way to do the same with the cursor, like `ctrl+d` or `ctrl+u` in vim. I personally think both types of scrolling should be available. What's your take on that?

**Comment by jmacdonald** [comment]
@elshize having the cursor maintain its original position is a feature, in my opinion. It creates an implicit point of reference that you can always jump back to, regardless of the view/window position. :slightly_smiling_face:

It sounds like you're trying to browse the buffer, and then work within a region of interest once you've found it. I'm pretty sure leaning into amp's jump mode is going to help: scroll the buffer until you've found what you want, hit `f` to enter jump mode, and move the cursor to the precise location you're interested in. If you _don't_ find anything that interests you, you can always jog the cursor using `h/j/k/l` to skip back to your original view.

**Comment by elshize** [comment]
Yeah, I agree, being able to go back to where the cursor is, is quite nice. I guess I'm not that comfortable with the jump functionality yet, but your tip sounds reasonable. I'm excited to try it out :)

**Comment by jmacdonald** [comment]
@elshize glad to hear it! :slightly_smiling_face:
