### ISSUE TITLE
[Feature Request] Support for LibreSSL 3.0.0

### ISSUE THREAD

**Issue by jesselucas** [jmacdonald/amp#159]
Attempting to build amp on OpenBSD 6.6 and receive the following error:

```
error: failed to run custom build command for `openssl-sys v0.9.40`
```
```
thread 'main' panicked at '

This crate is only compatible with OpenSSL 1.0.1 through 1.1.1, or LibreSSL 2.5
through 2.9.0, but a different version of OpenSSL was found. The build is now aborting
due to this version mismatch.
```

**Comment by diegogangl** [comment]
That error comes from the [openssl-sys](https://github.com/alexcrichton/openssl-sys) crate, which is deprecated. The replacement, [openssl](https://github.com/sfackler/rust-openssl), supports the same OpenSSL versions though.

Which [openssl](https://man.openbsd.org/openssl.1) version do you have? Try with `openssl version -a`

**Comment by jesselucas** [comment]
```
 ~$ openssl version -a
LibreSSL 3.0.0
built on: date not available
platform: information not available
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) idea(int) blowfish(idx)
compiler: information not available
OPENSSLDIR: "/etc/ssl"
```

**Comment by diegogangl** [comment]
Apparently OpenSSL does support LibreSSL 3.0: https://github.com/sfackler/rust-openssl/issues/1121
They probably haven't updated the readme. It's a matter of switching crates here then

**Comment by jmacdonald** [comment]
Amp uses _very little_ of the `git2` crate. I've opted to simply remove its default features, one of which was SSH support, which in turn set a dependency on `openssl`. That should fix this particular build issue, as a side effect. Do let us know if this is the only build issue you encounter; I'm curious to see if it'll build on OpenBSD now.

**Comment by jesselucas** [comment]
Thank you! Now the build is running into an error locating libxcb. It's part of the base X and located in /usr/X11R6/lib/libxcb.a . Guessing the dependency https://github.com/rtbo/rust-xcb/ might need to add support for locating libxcb on OpenBSD?
