### ISSUE TITLE
[FEATURE REQUEST] Highlight kotlin files

### ISSUE THREAD

**Issue by dodalovic** [jmacdonald/amp#161]
Hi, thanks for nice editor!
One thing I noticed - syntax highlighting of `kotlin` source code doesn't work. 
Anything that can be done about it? 

Thanks!

**Comment by pbgc** [comment]
If you take a look at the documentation:

https://amp.rs/docs/configuration/#adding-a-new-definition

you can read that it's just a matter of searching for a .sublime-syntax definition file ... for example this one:

https://github.com/getzola/zola/blob/master/sublime_syntaxes/Kotlin.sublime-syntax

and putting it on amp syntax file folder (on macOS its ~/ApplicationSupport/amp/syntaxes/ ; on other systems read on the documentation how you can find the right place).

**Comment by dodalovic** [comment]
That helped a lot, sorry for being lazy to figure it out myself :|
