### ISSUE TITLE
[BUG] File mode doesn't index all files

### ISSUE THREAD

**Issue by dodalovic** [jmacdonald/amp#162]
As described in the [docs](https://amp.rs/docs/usage/#using-the-file-finder) - I expect that, when I go to my project directory, and let's say I'd like to list all `.java` files in there - I should just type: 

```
java
```

and that should list all `.java` files in the directory. 
It lists just a few. 

Not sure if I'm doing something wrong there

Thanks

**Comment by pbgc** [comment]
The objective of the file finder is not list all files but opening a file by fuzzy matching (it shows you on the list up to 5 matches): 
https://amp.rs/docs/usage/#using-the-file-finder

This is the same one several other places like in the great feature of symbol jumping: https://amp.rs/docs/usage/#jumping-to-symbols

**Comment by pbgc** [comment]
Adding to what I wrote earlier: It does index all files for sure! (just try to insert some fragments) but doesn't show them all! it only shows up to 5 matches.
