### ISSUE TITLE
[PERFORMANCE_ISSUE] Paste is very slow

### ISSUE THREAD

**Issue by dodalovic** [jmacdonald/amp#164]
When I use paste (`p`), that is very very slow. 

Sometimes I even don't get pasted what I expected, but less. 

Also - I noticed that formatting is not preserved when pasting.

**Comment by pbgc** [comment]
Something strange is happening with you ...  I never had that problem!

I can tell you that I just tried to open a blank python file with amp and pasted 3421 lines (that I copied from another python file) and it was almost instantaneous.

**Comment by pbgc** [comment]
And formatting is definitely preserved when pasting!

**Comment by dodalovic** [comment]
There seems to be an issue when trying to paste via `cmd+v`.
