### ISSUE TITLE
Does it support vimscript?

### ISSUE THREAD

**Issue by dhilst** [jmacdonald/amp#172]
Does it support vimscript?

Are you willing PRs?

Regards

**Comment by jmacdonald** [comment]
Hi @dhilst! While amp is _inspired_ by Vim, I have no intent to support Vimscript. I've thought about adding a Ruby interpreter for plug-ins via `mruby`, but haven't found the need for a plug-in system just yet. :slightly_smiling_face:

**Comment by dhilst** [comment]
Okay, I'm searching a rust project to contribute and have great interest in parsers

**Comment by jmacdonald** [comment]
Amp's [underlying syntax highlighting library](https://github.com/trishume/syntect) might be of interest to you, then! Contributions there help amp indirectly, and I believe they're working on a rewrite around the `fancy-regex` crate. :slightly_smiling_face:

**Comment by dhilst** [comment]
I will take a look, thanks
