### ISSUE TITLE
amp 0.6.2 doesn't work with CRLF (\r\n) files

### ISSUE THREAD

**Issue by rialpamu** [jmacdonald/amp#182]
can be reproduced by a very simple file.
Example CSV (from https://tools.ietf.org/html/rfc4180#page-2):
```
aaa,bbb,ccc CRLF
zzz,yyy,xxx CRLF
```
Navigation key 'j' or cursor down doesn't work.
Jump keys ('f', '\'') show an empty screen (with the small sample csv file above);
other effects with bigger files.
Sometimes some random text from the terminal invoking amp is displayed.

**Comment by pbgc** [comment]
This is know and documented: https://amp.rs/docs/#encoding
It was already submitted before: https://github.com/jmacdonald/amp/issues/52

**Comment by rialpamu** [comment]
But CRLF are not only Windows line endings.
This was my motivation to use a CSV example file from the CSV specification.
