### ISSUE TITLE
website is down

### ISSUE THREAD

**Issue by pbgc** [jmacdonald/amp#189]
Hi,

It seems amp.rs is down. It seems a dns problem.

Thanks

**Comment by jmacdonald** [comment]
Hi @pbgc! Hmm, it's been working from me; might be a Cloudflare-related outage? Is it still inaccessible for you?

**Comment by pbgc** [comment]
@jmacdonald 
I'm using Quad9 DNS (www.quad9.net) and it seems amp.rs is blocked (you can search this on the site) there because ThreadConnect Thread Intelligence Provider listed it.... And this is only some days ago and only now I saw that this is the problem. Sorry.

**Comment by pbgc** [comment]
@jmacdonald I'm only leaving this open because I don't know if you want to contact for a false positive. 
https://www.quad9.net/result/?url=amp.rs

**Comment by pbgc** [comment]
Ok. It seems it was unblocked.
