### ISSUE TITLE
How to run amp with sudo command

### ISSUE THREAD

**Issue by israteneda** [jmacdonald/amp#199]
Hello everyone, the project is very cool.
I'm new with amp and no experience Linux user.

I'd like to use amp with sudo, like:
`sudo amp`
and the result is:
`sudo: amp: command not found`
but if I type:
`sudo vim`
then, vim opens

**Comment by knkski** [comment]
This looks like an issue with `PATH`. You'll probably see different locations if you do `which amp` and `which vim`. The easiest way to fix this is to run `sudo $(which amp)`.

**Comment by sesar54** [comment]
A common issue with all programs installed with cargo. All binaries are placed in `$HOME/.cargo/bin/` a place which the user root has no path to. One solution is to check if your packager manager has the amp binary and install it global on your system. I can say that arch linux has it in the aur.

**Comment by israteneda** [comment]
Thank you for your answers, I'll try it
