### ISSUE TITLE
Elastic tabstops

### ISSUE THREAD

**Issue by notramo** [jmacdonald/amp#20]
Amp should support [elastic tabstops](http://nickgravgaard.com/elastic-tabstops/).

**Comment by watzon** [comment]
Yes please! Although I would also like the idea of having support for plugins and this could be implemented as such.

**Comment by notramo** [comment]
I think it have to be implemented in the core, see the [similar issue with Kakoune](https://github.com/mawww/kakoune/issues/1682#issuecomment-362781663)

**Comment by notramo** [comment]
I think it's not very relevant today, so I'm closing this issue.

Most autoformatters (e.g. `dprint`, Biome) can replicate this behavior with spaces, and provide LSP formatting, but their CLIs are also very fast.
Some languages (e.g. Crystal, Zig) use spaces for formatting in the official tool (`zig fmt`, `crystal tool format`).
