### ISSUE TITLE
[Feature Request] Visual Block Mode

### ISSUE THREAD

**Issue by mrlogick** [jmacdonald/amp#207]
I don't think it's already implemented.
It would be great to edit in column, like in Vim (Ctrl-v).
But maybe there's already an alternative. For example if you could record commands with "q" you could edit many columns simply by repeating the commands over the lines.

**Comment by erf** [comment]
I think multiple cursors would be a great alternative to block mode, and a great addition to `amp`. Both `vis` and `vscode` support this now, and i think it's a more versatile as you can use the same vim commands as you are used to on a single cursors. Also in combination with a search where you add a cursor per search match, it is fantastic.

**Comment by mrlogick** [comment]
You are really right. Multiple cursors is the way. you can close I think.
