### ISSUE TITLE
Syntax highlighting broken

### ISSUE THREAD

**Issue by samscott89** [jmacdonald/amp#22]
Hey.

Awesome project!

Just noticed the syntax highlighting appears to be broken. I don't think it's capturing the end of scopes properly?

![amp-highlighting-rust](https://user-images.githubusercontent.com/13355482/35450747-eace37d0-028e-11e8-8adf-3d0494eb0249.png).

**Comment by wlcx** [comment]
![image](https://user-images.githubusercontent.com/3065381/35512019-2a65617a-04f6-11e8-8635-4f1ae56bdf33.png)

Seeing similar issues with go files
Amp: 0.3.2
OS: Ubuntu Artful

**Comment by ccapitalK** [comment]
![image](https://user-images.githubusercontent.com/12678164/35677004-1e5a1ce6-07a2-11e8-90d5-1c84e126e2f8.png)
Seeing similar issues with python as well.
Amp: 0.3.2
OS: Arch Linux

**Comment by Jackojc** [comment]
Similar issues with C++.
Version: 0.3.4_2
OS: Void Linux

**Comment by Jackojc** [comment]
Is it the internal syntax for C++ that's messing up or is it elsewhere? Would it be possible to override the default C++ syntax file with an alternative that does work?

**Comment by jmacdonald** [comment]
@Jackojc no, unfortunately this is a bug in amp. The good news is, it's what I'm working on at the moment, and is the last blocking bug fix before the `0.4.0` release. :slightly_smiling_face:

**Comment by samscott89** [comment]
For anyone else with this issue, there was more discussion of this in #61. Though I assume the workaround proposed there is about to be superseded :)

**Comment by jmacdonald** [comment]
@Jackojc sadly, no. I've been short on time over the last month and haven't been able to give it the attention it needs to prevent blocking a long overdue release. It'll be the first issue on the table, now that `0.4.0` is out the door! :slightly_smiling_face:

**Comment by Jackojc** [comment]
No worries at all! I understand this is just a side project of your and you have better things to be doing. <3

**Comment by jmacdonald** [comment]
This fix has landed in master; please do try it out when you have a moment. If there are no major issues, I'll cut a new official release.

Thanks for being patient!

**Comment by ccapitalK** [comment]
I've tried it out a bit, everything seems to work. Nice job!
