### ISSUE TITLE
Building fails on Fedora 34

### ISSUE THREAD

**Issue by Alekhine51** [jmacdonald/amp#227]
This is my first time trying this software. I installed rust and cargo, plus all dependencies, via dnf, and followed the install instructions exactly. Building failed with the following error codes:

```
  = note: /usr/bin/ld: cannot find -lxcb
          /usr/bin/ld: cannot find -lxcb
          /usr/bin/ld: cannot find -lxcb
          /usr/bin/ld: cannot find -lxcb
          collect2: error: ld returned 1 exit status
```

`error: linking with cc failed: exit code: 1`

These seemed to be the most relevant parts of the message. They were in huge blocks of unreadable mess that I couldn't make sense of.

Thanks in advance for any help you might have. I use cargo very rarely.

**Comment by LincolnAuster** [comment]
You need to install the xcb dev package. I don't have fedora installed atm, but I believe it's `dnf install xcb-util-devel`

**Comment by Alekhine51** [comment]
> You need to install the xcb dev package. I don't have fedora installed atm, but I believe it's `dnf install xcb-util-devel`

That worked. Thank you.
