### ISSUE TITLE
Can't seem to use the splash screen?

### ISSUE THREAD

**Issue by jD91mZM2** [jmacdonald/amp#23]
When starting `amp`, I get
```
         Amp v0.3.2
© 2015-2018 Jordan MacDonald
```
in the middle of the screen.
Nothing else.
Is surely isn't supposed to happen... is it?

**Comment by jmacdonald** [comment]
It is! Hit `Space` to open the file finder from there and pick a file to edit. 😄

**Comment by jD91mZM2** [comment]
But... nothing happens? In fact, that makes it freeze and I have to terminate it with SIGTERM.

**Comment by jmacdonald** [comment]
Ah, it's recursively indexing the current directory and everything beneath it. That's bad UX on my part Amp is meant to be run in a project directory, at which point the indexing will happen quickly. Try stepping into a smaller directory and try it again. 🙂

**Comment by jD91mZM2** [comment]
OH LOL! I was doing it in my /home 😛
