### ISSUE TITLE
Drawing over History   

### ISSUE THREAD

**Issue by guy-who-googles** [jmacdonald/amp#234]
To reproduce:
1. Enter commands in terminal
1. Open and close amp
1. When scrolling back through your terminal, shell history is covered by amp's theme.

While this isn't terrible for bash, being unable to view ipython history makes ipython's `%edit _<line_in_history>` less intuitive.

**Comment by christoph-heiss** [comment]
Try installing the current git version of amp using:
```
cargo install --git https://github.com/jmacdonald/amp.git
``` 

This issue has been fixed with 293d57f519b2f672f740131b5b203672bbcda2db, but there hasn't been a release since that change, thus making a git install necessary.

**Comment by guy-who-googles** [comment]
I can confirm installing the latest version solves the issue, thanks!
