### ISSUE TITLE
Fedora 36

### ISSUE THREAD

**Issue by AstroMoon** [jmacdonald/amp#259]
cargo install amp

error: failed to compile `amp v0.6.2`, intermediate artifacts can be found at 
`/tmp/cargo-install1nGV97`

I tried the install again and:

`/tmp/cargo-installyJBhSp`

**Comment by lincolnauster** [comment]
Are there any other debug logs present? I.e., the output of `cargo build` on stderr?

My suspicion (off of no evidence :)) is that you're missing libxcb. You might want to try verifying that it's installed. See https://amp.rs/docs/installation/.

**Comment by AstroMoon** [comment]
Thanks for the reply! I am a "Windows refugee" with about six months of distro-hopping to settle on Fedora because of stability and the fact that this distro "just works". While I don't consider myself a newbie, there are many things that I don't know (yet), however, I am very comfortable in the terminal. In the cargo/rust ecosystem, how would I go about checking the debug logs and status of libxcb? I checked all the dependencies and revisited the installation process. Now I see this:
 
    = note: /usr/bin/ld: cannot find -lxcb
        collect2: error: ld returned 1 exit status
error: could not compile `amp` due to previous error
error: failed to compile `amp v0.6.2`, intermediate artifacts can be found at `/tmp/cargo-install7reBB4`

**Comment by lincolnauster** [comment]
> how would I go about checking the debug logs and status of libxcb?

What shows up when you `cargo build` or `cargo install`? It looks like you got it, though:

```
= note: /usr/bin/ld: cannot find -lxcb
    collect2: error: ld returned 1 exit status
```

The above is an indication that the build system isn't able to link with libXcb (which amp requires so that copying/pasting uses the system's clipboard). If I'm remembering Fedora right, I'd guess that `dnf install libxcb-devel` and a retry at compiling would fix it. Have you done that/does it help any?

**Comment by AstroMoon** [comment]
wow!
Thanks, after running the 'libxcb' script, it runs.
New issue: works in BASH but not ZSH or FISH (?)

**Comment by AstroMoon** [comment]
edit:
got it going in all shells,
thx again!
