### ISSUE TITLE
Compilation failure in macOS

### ISSUE THREAD

**Issue by svraghavan** [jmacdonald/amp#26]
=> git clone https://github.com/jmacdonald/amp.git
=> cd amp
=> cargo build --release 

Compiling same-file v1.0.0
   Compiling percent-encoding v1.0.0
   Compiling itoa v0.3.4
   Compiling yaml-rust v0.3.5
   Compiling log v0.3.8
   Compiling utf8-ranges v0.1.3
   Compiling cc v1.0.1
   Compiling rustc-serialize v0.3.24
   Compiling app_dirs v1.1.1
   Compiling regex-syntax v0.4.1
   Compiling libc v0.2.32
   Compiling unicode-xid v0.0.4
   Compiling block v0.1.6
error[E0619]: the type of this value must be known in this context
  --> /Users/venkat/.cargo/registry/src/github.com-1ecc6299db9ec823/app_dirs-1.1.1/src/imp/platform/macos.rs:10:40
   |
10 |         Ok(Component::RootDir.as_ref().into())
   |                                        ^^^^

error: aborting due to previous error

error: Could not compile `app_dirs`.
warning: build failed, waiting for other jobs to finish...
error: build failed

Pls let me know if you want me to try anything and provide more info.

More Info:

macOs High Sierra
version 10.13.2

**Comment by jmacdonald** [comment]
Currently compiling on High Sierra `10.13.3`, with Rust `1.23.0`. Mind telling me what version of Rust you're running?

**Comment by netgusto** [comment]
Same here:
```
Compiling app_dirs v1.1.1
error[E0619]: the type of this value must be known in this context
  --> /Users/.../app_dirs-1.1.1/src/imp/platform/macos.rs:10:40
   |
10 |         Ok(Component::RootDir.as_ref().into())
   |                                        ^^^^

error: aborting due to previous error

error: Could not compile `app_dirs`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `amp v0.3.2 (https://github.com/jmacdonald/amp/?tag=0.3.2#5ec29b3e)`, intermediate artifacts can be found at `/var/folders/...`

Caused by:
  build failed
```

➜  ~ cargo -V
cargo 0.25.0-nightly (a88fbace4 2017-12-29)

MacOS High Sierra 10.13.3

**Comment by netgusto** [comment]
Exact same error on MacOS High Sierra 10.13.3 after upgrading to latest nightly with `rustup update`

```
➜  ~ cargo version
cargo 0.26.0-nightly (91e36aa86 2018-01-25)
➜  ~ rustc -V
rustc 1.25.0-nightly (9fd7da904 2018-01-25)
```

**Comment by netgusto** [comment]
Compiles fine on current stable for me.
cargo 0.24.0 (45043115c 2017-12-05) / MacOS 10.13.3

**Comment by svraghavan** [comment]
Yes, confirming that.

cargo -V
cargo 0.25.0-nightly (a88fbace4 2017-12-29)

**Comment by jmacdonald** [comment]
Thanks for digging in! Amp's [CI config](https://github.com/jmacdonald/amp/blob/master/.travis.yml#L2) only runs on Rust stable. I'll add a note to the documentation to that effect.

**Comment by jmacdonald** [comment]
Updated docs can be found [here](https://amp.rs/docs/installation/#building). Thanks for the head's up!
