### ISSUE TITLE
 [Bug]: (un)indenting within select line mode not working

### ISSUE THREAD

**Issue by KiaraGrouwstra** [jmacdonald/amp#267]
in normal mode one may use `<`/`>` to (un)indent a line.
it would be nice to be able to use this in batch for multiple lines using select line mode (`v`), but currently this doesn't work.

**Comment by jmacdonald** [comment]
Hi there! This definitely _should_ work; those `<`/`>` keybindings are set in the [default keymap](https://github.com/jmacdonald/amp/blob/71df4835f5b5156b0c2604d1528eb063bae69841/src/input/key_map/default.yml#L271-L272). 🤔

**Comment by KiaraGrouwstra** [comment]
perhaps this should become a bug report then.

- amp version: 0.6.2
- system: nixos
- can reproduce without a config

what other info might i get?

**Comment by pbgc** [comment]
@KiaraGrouwstra  @jmacdonald 
> it would be nice to be able to use this in batch for multiple lines using select line mode (v), but currently this doesn't work.

What you want to do works using V (to select whole lines) but not with v (https://amp.rs/docs/usage/#selecting-text)

**Comment by jmacdonald** [comment]
Ah, I didn't catch the lowercase `v` in your initial description! 😅 I've confirmed that the feature works as expected on nixOS, so @pbgc's helpful advice should settle this.

**Comment by KiaraGrouwstra** [comment]
ah sorry i missed that - and thanks!
