### ISSUE TITLE
request a new release

### ISSUE THREAD

**Issue by chenrui333** [jmacdonald/amp#268]
👋 it has been almost four years since last release, and it would be good to cut a new release for https://github.com/jmacdonald/amp/issues/222, thanks!

**Comment by jmacdonald** [comment]
Hello! See https://github.com/jmacdonald/amp/issues/222#issuecomment-1881019181, but we should have a new release over the next week. 😄

**Comment by Pheoxy** [comment]
> Hello! See https://github.com/jmacdonald/amp/issues/222#issuecomment-1881019181, but we should have a new release over the next week. 😄 

Thanks, just looked at this project and thought it was dead until I looked at the commits.

**Comment by jmacdonald** [comment]
Fixed via c4ed2d8. Also updated on [crates.io](https://crates.io/crates/amp).
