### ISSUE TITLE
Timeline for Amp

### ISSUE THREAD

**Issue by Selyss** [jmacdonald/amp#274]
Hello,

I recently discovered this project and think it would be fun to contribute to. I'm looking for some good issues to fix (and using the text editor myself) and am wondering if there's some kind of roadmap or timeline for the project. A lot of the issues are older and I'm having trouble getting a sense of how active the issues are and if they are still issues. The projects page also seems stale. If there's any page about editor direction or if there's a big focus for the editor right now, I'd love to try and assist with it.

This may be better as a discussion... let me know if I should repost this over there.

**Comment by jmacdonald** [comment]
Hi @Selyss!

Thanks for the offer, and the nudge to update the projects page. I'll think on some of the things I'd like to accomplish next and will update you once I've got something ready!

**Comment by jmacdonald** [comment]
Ok, I'm going to close this in favor of discussions, and I've started one to cover [broadening language/format support](https://github.com/jmacdonald/amp/discussions/278). 🙂
