### ISSUE TITLE
Is there a way to do "select until token X"?

### ISSUE THREAD

**Issue by caffo** [jmacdonald/amp#287]
So, for example, if I have:

```
<h1>foo bar zaz</h1>
```

The cursor is placed on the first `>.` I want to select everything until the next `<`. (foo bar zaz in this case) and be able to delete, yank, etc.

For reference, in Vim, to delete it, I would do t <` to delete the `h1` content.

**Comment by pbgc** [comment]
You can use `v` to start a text selection range and then `f` to to switch to jump mode and extend the selection to some place (may need to adjust the selection some chars after with the movement keys) and then and use `d` to delete the text

**Comment by caffo** [comment]
Perfect, thanks!
