### ISSUE TITLE
Add git feature documentation

### ISSUE THREAD

**Issue by Evidlo** [jmacdonald/amp#34]
The documentation mentions git integration, but I am unable to find any information on how to use this feature.

**Comment by jmacdonald** [comment]
Great point! They're rather minimal at the moment, but they're likely to be expanded. For the time being, I'll mention these here, but will follow up with some documentation updates.

You'll see the file's current status in the bottom right area of the status bar. You can also stage the current file by hitting `-` (the rationale for that was the plus sign above indicating an "add" action).

**Comment by Evidlo** [comment]
On another note, I'm not a huge fan of the way the docs are split between multiple sections.  I don't know if this is normal for MkDocs, but it makes it look like the `Overview` page makes up all of the documentation, when in reality the rest of it is hidden behind that hamburger menu at the top left or next arrow at the bottom right.  Easy to miss.

**Comment by jmacdonald** [comment]
Are you viewing on mobile or tablet? It's a responsive site, so it'll collapse the left-hand navigation menu when horizontal space is limited.

**Comment by Evidlo** [comment]
Yeah, it was collapsed (although the window isn't even that narrow).  Bad design in my opinion.  I thought all of the documentation was just that one page at first.
![](https://i.imgur.com/suq2J21.png)

Here's readthedocs.io at the same width, which does a much better job in my opinion:
![](https://i.imgur.com/7dhnP5a.png)

**Comment by jmacdonald** [comment]
Does it still show a "Next" link at the bottom? Agreed that it can be misleading, although I love the material mkdocs theme, otherwise. We might be able to tweak the breakpoints so that it's still expanded at that width.

**Comment by Evidlo** [comment]
It does.
