### ISSUE TITLE
Unable to save new buffer

### ISSUE THREAD

**Issue by robertsdionne** [jmacdonald/amp#36]
### Steps to reproduce:
* Create a new buffer with `B`.
* Save the new buffer with `s`.

### Expected
* Save the buffer, perhaps requesting a name beforehand.

### Actual
* Error: `"Unable to save buffer"`

**Comment by jmacdonald** [comment]
Thanks for this.

Saving new buffers has been planned for a while, but I've never gotten around to it; might as well start the discussion now. 🙂 

Here's an outline of what needs to happen to support this:

1. Add a new "name buffer" mode, with an input prompt.
2. Pre-populate the input with the current working directory (provided by the `Workspace` type); that'll be easier than working with relative paths.
3. On the "accept" action, write the buffer out.
4. If an error occurs, display it, _but don't return to normal mode yet_; we'll want to provide the opportunity to correct invalid input.

In the spirit of keeping things as simple as possible, at least for a first version, we should table additions like tab completion.

**Comment by ccapitalK** [comment]
In step 3, shouldn't the accept action set the path of the buffer before writing it out? Otherwise, the user would have to re-enter the file name every time they want to save. If so, I think we would need to modify scribe::buffer::Buffer to allow this, as I don't see any way of doing this currently.

**Comment by jmacdonald** [comment]
Available in `master`, now. Much thanks to @ccapitalK for getting this implementation started. 🍻
