### ISSUE TITLE
old termion fork doesn't build on arm / arm64 / musl

### ISSUE THREAD

**Issue by dten** [jmacdonald/amp#40]
I'd like to use this on Android (via termux) but changes were made early 2017 to fix termion on these targets. Your fork is something like October 2016 which hasn't got the fixes

**Comment by dten** [comment]
Great success! Thanks a lot!
![screenshot_20180201-071727_termux](https://user-images.githubusercontent.com/1019038/35665970-127a0dd2-0720-11e8-8451-a98a8d628d4c.jpg)

**Comment by jmacdonald** [comment]
You're welcome; I'm glad it's working!
