### ISSUE TITLE
Racer support

### ISSUE THREAD

**Issue by wpbirney** [jmacdonald/amp#41]
Is racer support planned in the future? I could look into it

**Comment by jmacdonald** [comment]
I've heard about racer, but haven't dug into it; have you got a link handy? Can't seem to find a reference to anything other than a Rack web server and the v8 Ruby bindings (therubyracer).

There's [another discussion](https://github.com/jmacdonald/amp/issues/37) relating to general language support that might be related. If racer supports the Language Server Protocol, this would align nicely 👌.

**Comment by wpbirney** [comment]
@jmacdonald i was referring to https://github.com/racer-rust/racer for rust code completion

**Comment by vks** [comment]
The RLS supersedes racer, so I think this should be closed in favor of #37.

**Comment by wpbirney** [comment]
@vks agreed
