### ISSUE TITLE
Editor is slow for large files

### ISSUE THREAD

**Issue by matklad** [jmacdonald/amp#42]
Hi!

Looks like the editor significantly lags near the end of huge files. For example, for https://github.com/rust-lang/rust/blob/5e7fd65419384e5322fe18d3c6ea37e59860a9bc/src/libsyntax/parse/parser.rs, cursor movements and symbol navigation feels very slow near the end of the file. 

Also, I really admire the focus on the *right* usability things! `Enter`, `f`, fuzzy file search from the get-go are really crucial feature from my point of view, 👍 ❤️

**Comment by jmacdonald** [comment]
Hi @matklad! Thanks for the kind words; definitely feels like we're aligned on priorities for an editor. 🙂 

The lexing/syntax highlighting is to blame here. Amp (or its associated `scribe` library) needs to implement caching for its `TokenIterator`. I've gone through a few designs on the whiteboard in the past, but none of them were a clear winner; it gets tricky with lazy evaluation and zero-copy references into the buffer.

I'll have another look at design options for a caching solution, and will post here when I have something worth sharing.

**Comment by matklad** [comment]
Heh, I happen to have a partially working incremental Rust parser over here: https://github.com/matklad/fall/tree/acf151d1edb96d3724db1eab8a8ff114c5671de9/lang/rust :) 

It's definitely not ready for production use yet, but it's already

- moderately fast: https://youtu.be/kcG_hduJGtM
- allows to build some fancy stuff on top: https://youtu.be/KyUUDcnOvUw

:)

**Comment by jmacdonald** [comment]
@matklad I've added incremental parsing to amp's buffer renderer, which is available as of [0.5.0rc1](https://github.com/jmacdonald/amp/releases/tag/0.5.0rc1). I've tested it on the `parser.rs` file you linked and it scales quite nicely; take it for a spin and let me know what you think!

**Comment by jmacdonald** [comment]
Implemented as of [0.5.0](https://github.com/jmacdonald/amp/releases/tag/0.5.0).
