### ISSUE TITLE
Compiled binary for x86_64

### ISSUE THREAD

**Issue by rickyhan** [jmacdonald/amp#44]
Can you include some compiled binaries in release?

**Comment by jmacdonald** [comment]
[As requested](https://github.com/jmacdonald/amp/releases/tag/0.3.2).

You'll still need the runtime dependencies as specified in the [installation instructions](https://amp.rs/docs/installation#dependencies), if they're not already installed. We're automating this at the moment; if you're interested in following that, see #32.
