### ISSUE TITLE
Share work with iota?

### ISSUE THREAD

**Issue by Anachron** [jmacdonald/amp#50]
https://github.com/gchp/iota seems to be similiar to this project, there may be things from both sides that can be used on the other projects.

**Comment by vks** [comment]
There is also https://github.com/google/xi-editor.

**Comment by jmacdonald** [comment]
I've actually built Amp's core library as a [separate crate](https://github.com/jmacdonald/scribe) from the start, which contains all of the non-opinionated bits (data structures, syntax highlighting, workspace management, etc.) that could be re-used to build another text editor, so I _think_ we're in good shape on that front. 🙂
