### ISSUE TITLE
Documentation of keybinds is incomplete

### ISSUE THREAD

**Issue by vks** [jmacdonald/amp#54]
Commands not mention in the docs (besides the ones fixed in #53):

* Undo (`u`) and redo (?).
* Delete and change to end of line (`D`, `C`).

There are probably others I'm missing.

**Comment by jmacdonald** [comment]
Have a look at the tip below the [key bindings documentation](https://amp.rs/docs/configuration/#key-bindings); there's a reference to the `application::display_default_keymap` command that will help you out.

I'll update the documentation with a note indicating that we can't cover all of the functionality there, and reference the aforementioned command for a complete list (which will _always_ be kept up to date as it's compiled into `amp` itself).

**Comment by skyfaller** [comment]
For anyone who is dying to read the key bindings on Github, the relevant file appears to be here: https://github.com/jmacdonald/amp/blob/master/src/input/key_map/default.yml
