### ISSUE TITLE
application::exit exits right away even with unsaved buffers

### ISSUE THREAD

**Issue by BlackYoup** [jmacdonald/amp#57]
`buffer::close` asks if we want to exit if the buffer hasn't been saved, but `application::exit` doesn't. Shouldn't `application::exit` ask that too ?

**Comment by mjswensen** [comment]
Looks like this is intentional and a recommended pattern is outlined in the docs: https://amp.rs/docs/usage/#exiting

**Comment by BlackYoup** [comment]
Oh, I didn't see that note!

Alright, it makes sense. I happened to close amp when typing `:x` (I mapped `:` to the command input, and just typing `x` in the search makes `application::exit` the first result :D). Vim habits.
