### ISSUE TITLE
How to do basic refactoring tasks.

### ISSUE THREAD

**Issue by guillaumecherel** [jmacdonald/amp#58]
How do you do some basic repetitive refactoring tasks like renaming all occurrences of a variable name in a file without a replace command? I know that you are planning to add it, but I was curious if there were another way to do something like that. Or do you use other tools for it?

I like the simplicity of amp, efficient without too many commands, and intuitive ones (like the jumping approach for moving around). I hope you can keep it in this direction.

**Comment by jmacdonald** [comment]
Thanks for the kind words, @guillaumecherel! It's a little awkward at the moment, but the easiest way to do a search and replace is as follows:

1. Do a search for the term you're looking to replace.
2. When the first result is selected, hit `c` to change it, and type the replacement value.
3. Copy the replacement value (using `v` for visual mode, moving the cursor, and then `y` to yank)
4. Hit `n` to enter search mode and highlight the next result.
5. Hit `p` to paste/replace the result with the yanked content, and move to the next result.
6. Keep hitting `p` until all of the occurrences are replaced.

Steps 1-5 will eventually be addressed with an explicit replace mode that will allow you to specify the replacement value. Still needs some thought to make the UX intuitive, but we'll eventually add support for it!

**Comment by pbgc** [comment]
@guillaumecherel Maybe this should be in the documentation! I've been using amp regularly and was really missing the search&replace feature ... but this is enough for me while waiting for the eventual replace mode.

**Comment by jmacdonald** [comment]
Added some [documentation](https://amp.rs/docs/usage/#replace) for this; thanks for reporting it!
