### ISSUE TITLE
File search slow to open in directories with many files

### ISSUE THREAD

**Issue by puradox** [jmacdonald/amp#59]
Upon opening `amp` in the home directory and pressing `Space` to search, the program blocks for 30-40 seconds before being greeted by the search screen.

<img width="762" alt="screen shot 2018-01-31 at 8 55 41 am" src="https://user-images.githubusercontent.com/941763/35636052-d9b07808-0664-11e8-80ba-6f9b2be45d35.png">

Environment:

OS: macOS 10.13.2
Processor: 2.8 GHz Intel Core i7
Memory: 16 GB 2133 MHz
Graphics: Radeon Pro 555

Installed via cargo: `cargo install --git https://github.com/jmacdonald/amp/`

**Comment by BlackYoup** [comment]
I guess that's related to what's explained here: https://github.com/jmacdonald/amp/issues/23#issuecomment-360855599

**Comment by jmacdonald** [comment]
Right! Open mode recursively indexes the current directory, so switching to it in a high-level directory is going to be slow. Amp is meant to be run inside of a project directory.

I'll make a note to update the docs to indicate this. 🙂

**Comment by puradox** [comment]
@jmacdonald Ah, I see. A note in the documentation would definately help avoid some confusion.

**Comment by jmacdonald** [comment]
Thanks for the report, @puradox!
