### ISSUE TITLE
Scroll slow and can not stop on mac.

### ISSUE THREAD

**Issue by jinfagang** [jmacdonald/amp#60]
Hi, this text-editor are so nice. Just only one question on mac, if I scroll it down using touch board or using scroll on mouse, the view will continue scroll down and hard to stop it. Seems this is very slow when scroll, any fix for this?

**Comment by jmacdonald** [comment]
Hi @jinfagang! Thank you. 😄

Amp doesn't have mouse support. You're recommended to use `m` and `,` to scroll down/up, respectively. I'll add a note to update the documentation to that effect. 🙂

**Comment by jmacdonald** [comment]
Also, the **Key Reference** note at the top of the [usage documentation](https://amp.rs/docs/usage/) will tell you how to view all of the default key bindings.

**Comment by jinfagang** [comment]
@jmacdonald I mainly using mac touch board which is 2-fingers scroll down gesture, seem effect as mouse scroll button. But this action will cause text continues scroll down. vim shall not happens this. I can navigation using arrow buttons just too slow when scroll down masive text files. If this not an issue, then I'd better get custom to `m` and `,` key bindings. Many thanks jmac.

**Comment by jmacdonald** [comment]
@jinfagang mouse/touchbar/etc. support is unlikely to land in Amp. It's _really_ meant to be keyboard-only. One of the biggest advantages of a modal editor is never taking your hands off of the keyboard. You do have the option of rebinding the scroll keys as you see fit, if `m` and `,` don't suit you:

```yaml
keymap:
  normal:
    J: view::scroll_down
    K: view::scroll_up
```

Hope that helps! 🙂

**Comment by jinfagang** [comment]
This is very nice!

**Comment by jmacdonald** [comment]
I'm going to close this for now, @jinfagang. I hope keymap configurations are good enough for now! 🙂
