### ISSUE TITLE
amp freezes activating open mode in some situations

### ISSUE THREAD

**Issue by pbgc** [jmacdonald/amp#62]
When inside a folder with a smaller number of files (for example in a project folder), using space I can open files in the current folder and below without any problem.
If I invoke amp for example in my home folder and hit space (for example to try to open .bashrc or any other file), amp freezes and does not respond to Q or any other key and I have to kill the process. I suspect it's because of the large number of files in the folders bellow ?
Congrats for your work in amp! I'm looking forward for the evolution!

MacOS 10.13.3
amp 0.33 compiled with cargo

**Comment by pbgc** [comment]
I'M SORRY .... Just missed the:

> This will recursively index the current directory and all subdirectories. It's meant to be used in project directories; don't use it from paths like / or ~.

Please close this issue and I apologize ... Just left it open to suggest that amp should not freeze and keep responding to Q to be able to at least quit ...

**Comment by jmacdonald** [comment]
No worries, @pbgc! Opening #68 to address this, indirectly. 🙂
