### ISSUE TITLE
What *xcb* package to install on Ubuntu?

### ISSUE THREAD

**Issue by bmusin** [jmacdonald/amp#64]
Hi.
When I build, it fails, because when passing `-lxcb` it doesn't find library.
When I do `apt search libxcb` it lists long list of library packages.
What exact package I need? Don't want to guess by installing all of them.
Thanks.
Ubuntu 17.10

**Comment by jmacdonald** [comment]
libxcb1-dev should do the trick! Will have to update the docs with Ubuntu
specific instructions.

**Comment by bmusin** [comment]
Thanks, it works.
