### ISSUE TITLE
Installing via homebrew fails with an error

### ISSUE THREAD

**Issue by jamiedumont** [jmacdonald/amp#66]
Afternoon!

I've been having some problems installing amp via homebrew. Each time I try it fails with the following:

```
Undefined symbols for architecture x86_64:
    "_OPENSSL_add_all_algorithms_noconf", referenced from:
         _libssh2_init in liblibssh2_sys-c9c25b68c0e31c1d.rlib(global.c.o)
ld: symbol(s) not found for architecture x86_64

error: aborting due to previous error
error: Could not compile 'amp'.
```

This also appeared to semi-install a broken version of Rust. Trying to install Rust using the `curl` command would fail as there was already an existing copy of Rust installed, yet I couldn't use any of the Rust tools, or uninstall them as documented. After manually removing all references to Rust across the filesystem, I was able to install Rust using `rustup`. This may not be related to the issue, but noticed it after trying the `homebrew` install (I did not have Rust installed beforehand).

---

Afterwards I tried compiling amp myself using `cargo` and that works without any issues.

I'm running on macOS High Sierra: 10.13.3 and homebrew is attempting to install from `amp-0.3.2.tar.gz`

Thanks for your hard work on amp! I've yet to give it a proper go, but really like the look of it, and many of the thoughts and decisions behind the project. It may just be replacing nvim for me!

Cheers, Jamie.

**Comment by jmacdonald** [comment]
Hi Jamie!

I'm actively working on addressing this issue. The idea is to get `amp` in `homebrew-core` so that folks can install pre-built binaries on macOS. That'd remove build dependencies, like a system-installed Rust. Appreciate the bug report; I'll be sure to update you here when it's fixed! 🙂

**Comment by jmacdonald** [comment]
I've updated the Homebrew formula; a `brew update && brew install amp` should now do the trick. Thanks for reporting this! 🙂

**Comment by bradparks** [comment]
though not exactly related to the same issue, I was trying to install using Homebrew, and got this error:

`Errno::EACCES: Permission denied @ dir_s_mkdir - Logs/Homebrew`

Which for me, meant I had to fix permissions as detailed here:
https://github.com/Homebrew/homebrew-cask/issues/2101

`sudo chown -R <username> /Users/<username>/Library/Logs`
