### ISSUE TITLE
Exit editor after last buffer is closed

### ISSUE THREAD

**Issue by Eriton33** [jmacdonald/amp#67]
When using amp in combination with file managers like ranger, is is very annoying to have amp still running after a file&buffer has been closed.

When editing files from the context of the file manager, it would be nice to be able to be able close the file abd be right back at the file manager. However with amp, after closing the last buffer, the application itself has to be closed in a second step.

I am not aware of any way to change this behavior, but there should be an option to have amp shut down after the last buffer has been closed

**Comment by jmacdonald** [comment]
Hey, @Eriton33. I'm not sure if you're aware, but you can hit `Q` with a buffer open and Amp will quit immediately; there's no need to close open buffers using `q` beforehand.

If you're concerned that you might forget to save the buffer before quitting like that, you can always create a key binding (uppercase `W` in this example) that saves the current buffer and quits:

```yaml
keymap:
  normal:
    W:
      - buffer::save
      - application::exit
```

If the `buffer::save` command fails for any reason, Amp won't quit and the error will be displayed.

**Comment by jmacdonald** [comment]
Closing this as it's configurable behaviour; do let me know if that's _not_ the case.
