### ISSUE TITLE
scrolling doesn't take word-wrap into account

### ISSUE THREAD

**Issue by jedahan** [jmacdonald/amp#72]
I've noticed that sometimes, not always, i have to `cursor::move_{down,up}`  waaay past the bottom of the window.

On an inkling, tested against a file with short lines, and a couple of really long lines.

Turns out the number of `move_down` I need to do before it starts scrolling is exactly the number of wrapped lines.

**Comment by jedahan** [comment]
might be a problem in scribe

**Comment by jmacdonald** [comment]
Great observation! I've come across this bug, but didn't notice the association to wrapped lines, and it makes perfect sense. The `ScrollableRegion` type isn't aware of line wrapping when scrolling the cursor into view.

**Comment by jmacdonald** [comment]
Fixed via #80. Thanks for the report, and the initial line-wrapping tip, @jedahan!
