### ISSUE TITLE
Theme loading problems

### ISSUE THREAD

**Issue by rahim** [jmacdonald/amp#73]
Hello!

In OSX, my amp settings dir appears to be `~/Library/Application Support/amp`

I created a themes directory there and placed the monokai extended theme there (copied out of my sublime config).

In amp, theme mode doesn't seem to see the theme. If I set the theme in amp's `config.yml`, starting amp yields an entirely blank terminal window, but amp is functioning - blind I can switch to theme mode and select the bundled solarized which then causes the default no buffers display to show. This seems to be the handling for any theme that is simply not found because it occurs if I change the theme config var to garbage.

It's not clear to me why my theme is not found though?

**Comment by jmacdonald** [comment]
@rahim can I ask you to attach the theme in question? I'd love to try this locally. 🙂

**Comment by rahim** [comment]
The original theme was https://gist.github.com/rahim/1021fa9d3512347b0c84d7ed60006d82

But I've since tried clearing my themes dir and added in a copy of one of the bundled solarized themes (modifying file name, name and uuid to avoid collision) and this also doesn't in Theme mode.

I wonder whether there's something simple wrong with my paths?

(I'm using amp 0.3.2)

**Comment by jmacdonald** [comment]
Ah, [theme loading](https://github.com/jmacdonald/amp/commit/6368cb622d38e64cfab270a838600ef5a4483861) hasn't landed in a tagged version yet; it's only available on `master` at the moment.

I'll publish a new 0.3.4 release tonight. :slightly_smiling_face:

**Comment by jmacdonald** [comment]
The [0.3.4 release](https://github.com/jmacdonald/amp/releases/tag/0.3.4) is now available. I've updated the Homebrew formula and AUR build scripts as well.

Do feel free to re-open this issue if you have problems using theme loading in the latest release!
