### ISSUE TITLE
Transparency in terminal emulator does not play nice with amp

### ISSUE THREAD

**Issue by redoxeon** [jmacdonald/amp#74]
I've tested this with vim and nano to see if they do it too, but it's just amp that does it. It might be the fact that I'm currently running Linux in a VM, but I'm not sure if that would cause it? I've included images to show what I mean because I'm not sure the right way to describe it. 

In the last picture, sometimes it will make the background green or yellow if that was the last background color before I typed `clear`

I'm on Antergos, and am using Alacritty as my terminal emulator (both are latest versions).

Normal:
![normal look](https://user-images.githubusercontent.com/10731372/37350020-6459a81e-269d-11e8-8fb5-d73034af44db.PNG)
When trying to edit a file:
![messes up transparency on close](https://user-images.githubusercontent.com/10731372/37350026-68b68044-269d-11e8-90f0-f50639c204ed.PNG)
After trying the `clear` command to fix it:
![after clear command to try to fix it](https://user-images.githubusercontent.com/10731372/37350654-f5e6b8d4-269e-11e8-892b-36bdec27a70a.PNG)
Alternate after typing clear:
![yellow background](https://user-images.githubusercontent.com/10731372/37351655-2ce5366a-26a1-11e8-983d-a0fc2e013e47.PNG)
Typing over itself in weird ways:
![typing over itself](https://user-images.githubusercontent.com/10731372/37351689-3b64f39c-26a1-11e8-8e21-cd5b2d0f5e3a.PNG)

**Comment by jmacdonald** [comment]
![transparency](https://user-images.githubusercontent.com/458253/37573889-cf62cc9a-2af2-11e8-9dea-7511a6f39102.png)


Seems okay running in Alacritty on OS X High Sierra. I'll give it a shot on my Arch box tomorrow.
