### ISSUE TITLE
Slow scroll and strange characters inserted by amp while scrolling

### ISSUE THREAD

**Issue by pbgc** [jmacdonald/amp#78]
Hi,

When opening a big file with amp (for example a 2200 line .py file) and using J to go to the end .... then trying to scroll up with the arrow key .. the scroll is really slow and if the arrow key is keeped pressed it is buffered and amp keeps scrolling up slowly even if we stop pressing the up arrow. 

Being slow is not the problem ... there is another issue about that .... the problem is that I get "A" and "B" characters inserted sometimes in my text while the scroll happens .... (can't understand why 'A' and 'B' .... and it seems randomly, but I'm not sure)

**Comment by Jackojc** [comment]
This happens to me when using the trackpoint scroll on my Thinkpad X230 (Basically middle click scroll...), It's perfectly fine, however, when using PgUp, PgDwn and , or m.

**Comment by jmacdonald** [comment]
This is actually unsupported behaviour; I think Rustbox is translating these mouse events to keystrokes, but I'll need to dig in to find out.

To be honest, I'll likely follow up with a patch to ignore these events. You really should be using the keyboard for everything in amp. :heart:

**Comment by pbgc** [comment]
@jmacdonald
I never touch the mouse with amp! This is happening with the arrow key, scrolling up from the bottom in a big file (~2000 lines). When I scroll up using the Up key I get 'A' and 'B' caracters inserted sometimes.
I'going to test with another file

**Comment by pbgc** [comment]
@jmacdonald 
I'm using 0.4.0 now ... and I cannot replicate this behavior ... (I could with the same file and with previous release). Scrolling with the arrow keys in the end of a big file is very slow, but that is another story that will eventually solved.
I will close the issue.
