### ISSUE TITLE
Can't configure files formats without extension eg. Makefile

### ISSUE THREAD

**Issue by Shadlock0133** [jmacdonald/amp#79]
Makefiles require usage of hard tabs, so being able to set soft_tabs to false just for them would be useful. But it's currently impossible as Amp check file format by extension.

**Comment by erf** [comment]
[vis](https://github.com/martanne/vis) uses `file(0)` in addition to file extensions and also has a optional custom file detector - see [filetype.lua](https://github.com/martanne/vis/blob/master/lua/plugins/filetype.lua), maybe something similar could be used for amp.

**Comment by jmacdonald** [comment]
We match by extension in the preferences file, but there's no reason we can't fall back to full filename matching for common cases without extensions like `Makefile`. Thanks for the report, @Shadlock0133; you should be all set now. :slightly_smiling_face:

**Comment by jmacdonald** [comment]
Oh, in case the expected format wasn't obvious, the commit also updates the docs to provide an example; you can see that rendered [here](https://amp.rs/docs/configuration/#file-format-specific-options).
