### ISSUE TITLE
How to add new syntax aliases?

### ISSUE THREAD

**Issue by jedahan** [jmacdonald/amp#82]
For example, .sh highlights fine, but if I wanted ~/.zshrc to use that highlight, I'm not sure how. Especially since I can't find a sublime text syntax definition for zsh. It looks like the default syntax set is created by `https://github.com/trishume/syntect`

**Comment by TonioGela** [comment]
+1 I want that syntax too

**Comment by jedahan** [comment]
bump! I wanna highlight `Dockerfile`

**Comment by jmacdonald** [comment]
Okay, the first step to implementing this is going to be to add a syntax selection mode. That way, whether or not the file extension matches a given syntax definition, you'll be able to manually select one.

The second phase to this is going to be using that selection model to get a key that we can set in the preferences. While it's handy that the syntaxes themselves can set these, it would be good to have local overrides.

**Comment by jmacdonald** [comment]
Okay, a new [`syntax-mode` branch](https://github.com/jmacdonald/amp/tree/syntax-mode) is up if you want to take this for a spin. Hit `)` to enter syntax mode with an open buffer and you can (re)define its defined syntax. Search is case sensitive, at the moment; that'll be addressed before we merge. There's also no persistence yet; that'll also land before I merge the branch to master, but it's going to take much more work.

**Comment by jedahan** [comment]
Sweet! Worked for Dockerfile with a downloaded `Dockerfile.sublime-syntax`

**Comment by jmacdonald** [comment]
@jedahan I've merged this to `master` with one small tweak: [I've set the default keybind for the new syntax mode to `#`](https://github.com/jmacdonald/amp/blob/65180add121fecf07a6b45480744b73bf40f8d1f/src/input/key_map/default.yml#L58). Thought I'd mention that to avoid a surprise when you rebuild from `master` in the future. :wink:
