### ISSUE TITLE
Bump version?

### ISSUE THREAD

**Issue by jedahan** [jmacdonald/amp#83]
Is master stable enough to bump to 0.3.5? Would be nice to have the line buffer fix...

**Comment by jmacdonald** [comment]
One small fix I'd like to implement and I'm going to bump to `0.4.0`, considering the major threaded event loop rewrite. Thanks for the kick!

**Comment by jmacdonald** [comment]
@jedahan I've fixed the aforementioned scrolling issue (and added a default keybinding that I've been using as a user preference for the past few weeks).

Please take the latest master for a spin. I'm planning on using it over the next week; if I don't see any major regressions, I'll bump the version number to `0.4.0` as of  4e7a0c488bf486ab1fa078f9d3258305ba2f5503 and will push Arch/Homebrew/crates.io package updates.

**Comment by mseri** [comment]
Ping! Is it ready for release?

**Comment by jedahan** [comment]
I saw nothing out of the ordinary for me.

**Comment by mseri** [comment]
There is still the syntax highlighting bug with a fix in progress: https://github.com/jmacdonald/amp/issues/22

**Comment by pbgc** [comment]
Hi. Any news about this ?

**Comment by jmacdonald** [comment]
Hi @pbgc! I recently landed a fix for the syntax highlighting bug; I'm just trying to make the updated `scribe` API more ergonomic. I'll likely wrap that up this weekend and push an `0.4.0` release candidate that we can use for a week or so before making it official. I'll post in here when it's ready! :smile:

**Comment by jmacdonald** [comment]
I've been using the updated version with syntax highlighting fixes and it's not quite there yet. Considering that it's a non-trivial fix, I've decided to bring that issue forward and release `0.4.0` stable as-is.

You can find the GitHub release [here](https://github.com/jmacdonald/amp/releases/tag/0.4.0). The `amp` [crate](https://crates.io/crates/amp) and [AUR package](https://aur.archlinux.org/packages/amp/) have been updated, too.

Thanks for being patient! :slightly_smiling_face:
