### ISSUE TITLE
Website text "Install v0.3.2" is outdated

### ISSUE THREAD

**Issue by Shadlock0133** [jmacdonald/amp#86]
Didn't know where to post this.
There are two links: first is under logo, and second at the bottom of site.

**Comment by jmacdonald** [comment]
Thanks for the reminder; going to tackle this with a bit of JS that'll pull the latest release using the GitHub API.

**Comment by jmacdonald** [comment]
[This commit](https://github.com/jmacdonald/amp-website/commit/63c7c0bc9c2841e99563ab7222b4b3052d3a367f) adds dynamic version numbers to the amp website. Thanks for reporting this!
