### ISSUE TITLE
Failed to compile amp v0.4.0

### ISSUE THREAD

**Issue by VandaLHJ** [jmacdonald/amp#87]
error: failed to compile `amp v0.4.0`, intermediate artifacts can be found at `/tmp/cargo-installHxe3OV`

Caused by:
  multiple packages link to native library `onig`, but a native library can be linked only once

package `onig_sys v65.0.1`
    ... which is depended on by `onig v1.6.1`
    ... which is depended on by `syntect v1.8.1`
    ... which is depended on by `amp v0.4.0`
links to native library `onig`

package `onig_sys v68.0.1`
    ... which is depended on by `onig v3.2.2`
    ... which is depended on by `syntect v2.1.0`
    ... which is depended on by `scribe v0.6.3`
    ... which is depended on by `amp v0.4.0`
also links to native library `onig`
rustc 1.27.0 (3eda71b00 2018-06-19)
cargo 1.27.0 (1e95190e5 2018-05-27)

**Comment by kivikakk** [comment]
This was fixed in https://github.com/jmacdonald/amp/commit/abce597f94286cb238bacc5db7a14800f4689d90, there just hasn't been a release since.

**Comment by jmacdonald** [comment]
Given the fixes for syntax highlighting that have landed in master, I’ll
cut a 0.4.1 release that’ll help avoid this.

**Comment by jmacdonald** [comment]
Fixed via https://github.com/jmacdonald/amp/commit/558e62b26ea3b0ccf9051712e2017a6170f3450c. Thanks for the report, @VandaLHJ, and for the assist, @kivikakk!
