### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by florianjacob** [jmacdonald/amp#9]
Hi there, I just found this project, very promising. :smile:

I figured out I need to use nightly rust to compile it, but wen I try to run `./amp --help`, I get the following:

```
$ cargo run -- --help
     Running `target/debug/amp --help`
thread '<main>' panicked at 'Ran into an error trying to open --help.', src/models/application/mod.rs:60
note: Run with `RUST_BACKTRACE=1` for a backtrace
```

Also, (maybe related, maybe something different?), when I run `amp` without arguments, I get a blank terminal which doesn't respond to any keys (`CTRL^C` etc.), and I need to SIGKILL amp to stop it again.

I'm using rustc 1.8.0-nightly (4b615854f 2016-01-26) on Linux.

**Comment by jmacdonald** [comment]
Glad to hear you're interested! :smile: 

I haven't spent any time getting this ready for other users yet, but here's a quick rundown of how to use it:

`amp [path1] [path2] ...`

If you run `amp` without any arguments, you get an empty "workspace". Hit `0` to open the file finder to search for and open new files. Files are found using substrings/fragments, which you can split using spaces. An ideal search for a file at `src/models/applications/modes/open.rs` would use this term: `mod app open`.

_Most_ of the movement keys are similar to vim, but there are some large deviations. I've embraced the "easymotion" vim plug-in as the primary means of movement, but you can also use word-based movement; you can consult `src/input/modes/normal.rs` for a listing that should be _somewhat_ self-explanatory.

I'm going to treat this issue as a request for documentation, which is sorely needed; I'll follow up soon with something much more thorough and formalized!

**Comment by florianjacob** [comment]
Thans for the rundown, I managed to look around a little with that. Didn't know easymotion existed, and Ithink it's great to include that directly as a core feature. :smile: I was really impressed how far you already are, didn't expect that. Really nice!  I'll try to help out when I find the time.

**Comment by jmacdonald** [comment]
Glad to hear it, thanks! It has replaced Vim as my primary editor. There are a lot of other features; I'll let you know when the first draft of documentation is ready so you can have a look. :smile:

**Comment by jmacdonald** [comment]
Hey @florianjacob! I've been working on documentation for the past while, which can be found [here](https://amp.rs/docs). I'm going to close this issue for now; I'm documenting new features as they're added, so we should be caught up going forward!

**Comment by florianjacob** [comment]
It's really awesome to see how far amp has got in the last two years! :+1:
Installed the current version a while ago, the new docs helped me alot to get into it again. :sparkles:
