### ISSUE TITLE
Command `application::switch_to_open_mode ` can not work in home dir

### ISSUE THREAD

**Issue by LuoZijun** [jmacdonald/amp#92]
System: macOS

```bash
cd ~/
amp
```

`application::switch_to_open_mode` command can't search file on home dir.

**Comment by jmacdonald** [comment]
Hi @LuoZijun! Open mode should work, although it will take a long time for it to complete. You should see a message reading "Indexing x" where `x` is the absolute path to your home directory. If you're seeing the app _lock_, then [this issue](https://github.com/jmacdonald/amp/issues/62) should be re-opened, but I'd be surprised if that's the case. 🙂

**Comment by LuoZijun** [comment]
Oh, okay.
I can see `Indexing ...`, after about 80s everything is ok.
thank you.
