### ISSUE TITLE
Error compiling on alpine linux

### ISSUE THREAD

**Issue by jedahan** [jmacdonald/amp#95]
Might be a termbox issue?

```zsh
~ cat /etc/alpine-release
3.8.0

~ cargo version
cargo 1.28.0
```

```bash
error: failed to run custom build command for `termbox-sys v0.2.10`
process didn't exit successfully: `/tmp/cargo-installZ4DhuZ/release/build/termbox-sys-0ca8eb4d7f3df740/build-script-build` (exit code: 101)
--- stdout
running: "git" "clone" "https://github.com/nsf/termbox" ".termbox"

--- stderr
fatal: destination path '.termbox' already exists and is not an empty directory.
thread 'main' panicked at 'assertion failed: cmd.stdout(Stdio::inherit()).stderr(Stdio::inherit()).status().unwrap().success()', /home/micro/.cargo/registry/src/github.com-1ecc6299db9ec823/termbox-sys-0.2.10/build.rs:87:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by jmacdonald** [comment]
It's been a while since I've run into this, but I _think_ this is because you're missing Python. Termbox uses it under the hood during the install process, unfortunately. Make sure you've got it and all of the other dependencies installed, [as specified in the docs](https://amp.rs/docs/installation/#dependencies). If that doesn't fix it, do let me know!

**Comment by jmacdonald** [comment]
Yep, looks like [an issue with termbox-sys](https://github.com/gchp/termbox-sys/issues/11).

**Comment by jmacdonald** [comment]
I've put a temporary workaround in place. There are _two_ build issues related to termbox at the moment:

1. The `termbox-sys` crate doesn't clean itself (removing the old `.termbox` directory) before running its build steps again.
2. The upstream `termbox` library itself doesn't work with Python 3.7. I've added a patch to `termbox-sys` that points the cloned termbox build script to `python2`, while we wait for a fix upstream.

**Comment by jedahan** [comment]
Thank you!
