### ISSUE TITLE
Add documentation for creating new buffers/files

### ISSUE THREAD

**Issue by jonathandturner** [jmacdonald/amp#96]
I *just* started using amp, so there may be a better way to do this, but I noticed that it might be nice to be able to hit `space` and in addition to typing an existing file, also be able to type a new file you want. Maybe it confirms you want to create it and then you're in a new buffer attached to that file.

**Comment by Jackojc** [comment]
You can do this:
- Press "0" to enter command mode (I think that's what it's called)
- Search for `workspace::new_buffer`
- Press "s" to save
- It will prompt for a path

**Comment by jonathandturner** [comment]
Thanks for the help. `B`+`s` is a funny key combo, but it's easy to remember!

**Comment by Jackojc** [comment]
Ah! I knew there was a shortcut but I couldn't for the life of me remember it @jmacdonald .
